[package]
name = "yaque"
version = "0.3.3"
authors = ["Pedro Arruda <pedrobittencourt3@protonmail.ch>"]
edition = "2018"
description = "Yaque is yet another disk-backed persistent queue for Rust"
license = "Apache-2.0"
homepage = "https://github.com/tokahuke/yaque"
repository = "https://github.com/tokahuke/yaque"
keywords = ["queue", "persistent", "disk", "data-structures"]
readme = "readme.md"
exclude = ["data"]

[features]
default = ["recovery"]
recovery = ["sysinfo"]

[dependencies]
notify = "5.0.0-pre.2"
log = "^0.4"
sysinfo = { version = "0.14.5", optional = true }

[dev-dependencies]
rand = "0.7.3"
rand_xorshift = "0.2.0"
futures = "0.3.5"
simple_logger = "1.6.0"